export default {
  title: {
    dene: "Deneme yazısına {{var}} ekledim",
    home: "Ana sayfa",
    dashboard: "Gösterge Paneli",
    options: "Ayarlar",
    logout: "Çıkış",
    users: "Kullanıcılar",
    layouts: "Düzenler",
    fullName: "İsim Soyisim",
    email: "Eposta",
    password: "Şifre",
    retypePassword: "Şifre tekrar",
    trash: "Silinenler",
    permissions: "İzinler",

    description: "Açıklama",
    firstName: "İsim",
    lastName: "Soyisim",
    role: "Rol",
    roles: "Roller",
    username: "Kullanıcı adı",
    nickname: "Takma ad",
    image: "Resim",
    createdAt: "Oluşturulma tarihi",
    updatedAt: "Güncellenme tarihi",
    deletedAt: "Silinme tarihi",
    status: "Durum",
  },
  any: {
    title: "Başlık",
    content: "İçerik",
    search: "Ara",
    trash: "Silinenler",
    addNew: "Yeni Ekle",
    save: "Kaydet",
    body: "Gövde",
    noElementFound: "Öğe Bulunamadı!",
    shownRecord: "Sayfada gösterilen kayıt:",

    selectAll: "Hepsini Seç",
    customize: "Özelleştir",
    darkMode: "Karanlık Mod",
    noBorder: "Çerçeve Yok",
    fixed: "Sabit",
    collapsed: "Daralt",
    navFlat: "Düz Menu",
    navLegacy: "Miras Menu",
    navCompact: "Sıkı Menu",
    navChildIndent: "Menu Alt Girinti",
    navChildHideOnCollapse: "Menü Daraltıldığında Alt Elemanı Gizle",
    disableHoverFocusAutoExpand: "Hover/Odak Otomatik Genişletmeyi Devre Dışı Bırak",
    headerOptions: "Başlık Seçenekleri",
    sidebarOptions: "Kenarlık Seçenekleri",
    footerOptions: "Altbilgi Seçenekleri",
    smallTextOption: "Küçük Metin Seçenekleri",
    navbarVariants: "Menü Varyantları",
    sidebarVariants: "Kenarlık Varyantları",
    brandLogoVariants: "Marka Logo Varyantları",
    noneSelected: "Hiçbiri",
    primary: "Birincil",
    secondary: "İkincil",
    info: "Bilgi",
    warning: "Uyarı",
    success: "Başarı",
    danger: "Tehlike",
    indigo: "Çivit",
    purple: "Mor",
    pink: "Pembe",
    navy: "Lacivert ",
    lightblue: "Açık Mavi",
    cyan: "Camgöbeği",
    dark: "Karanlık",
    grayDark: "Koyu Gri",
    gray: "Gri",
    light: "Açık",
    white: "Beyaz",
    orange: "Turuncu",
    fuchsia: "Fuşya",
    maroon: "Bordo",
    lime: "Limon Yeşili",
    teal: "Deniz Mavisi",
    olive: "Zeytin Yeşili",
  },
  permission: {
    searchPost: "Yazı Arama",
    createPost: "Yazı Oluşturma",
    readPost: "Yazı Okuma",
    updatePost: "Yazı Düzenleme",
    deletePost: "Yazı Silme",
    searchUser: "Kullanıcı Arama",
    createUser: "Kullanıcı Oluşturma",
    readUser: "Kullanıcı Okuma",
    updateUser: "Kullanıcı Düzenleme",
    deleteUser: "Kullanıcı Silme",
    searchRole: "Rol Arama",
    createRole: "Rol Oluşturma",
    readRole: "Rol Okuma",
    updateRole: "Rol Düzenleme",
    deleteRole: "Rol Sil",
    searchPage: "Sayfa Arama",
    createPage: "Sayfa Oluşturma",
    readPage: "Sayfa Okuma",
    updatePage: "Sayfa Düzenleme",
    deletePage: "Sayfa Silme",
  },
  footer: {
    text: "Ne isterseniz",
    rights: "Tüm Hakları Saklıdır.",
    copyright: "Telif Hakkı"
  },
  login: {
    message: "Oturumunuzu başlatmak için giriş yapın",
    rememberMe: "Beni Hatırla",
    signIn: "Giriş",
    forgetPassword: "Şifremi unuttum",
    registerNew: "Yeni üyelik kaydı",
  },
  register: {
    message: "Yeni üyelik kaydı",
    register: "kaydol",
    alreadyMember: "Zaten üyeyim",
  },
  password: {
    message: "Şifrenizi mi unuttunuz? Burdan kolayca şifre alabilirsiniz.",
    requestNew: "Yeni şifre isteği",
    login: "Giriş",
  },
  notify: {
    languagePreferenceSaved: "Dil Tercihi Kaydedildi",
    deletedSuccessfully: "Başarılı şekilde silindi",
  },
  error: {
    emailIsWrong: "Email Hatalı!",
    usernameIsWrong: "Kullanıcı Adı Hatalı!",
    passwordIsIncorrect: "Şifre Hatalı!",
    accessTokenNotSent: "Access Token Gönderilmedi!",
    accessTokenNotFound: "Access Token Bulunamadı!",
    accessTokenExpired: "Access Token Süresi Doldu!",
    userNotFound: "Kullanıcı Bulunamadı!",
    firstNameMustBeString: "İsim Dize Olmalıdır!",
    lastNameMustBeString: "Soyisim Dize Olmalıdır!",
    roleNotAllowed: "Role İzin Verilmedi!",
    emailNotValid: "Email Geçerli Formatta Değil!",
    usernameMustBeSent: "Kullanıcı Adı Göndeilmedi!",
    passwordNotValid: "Şifre Uygun Formatta Değil!",
    passwordsNotMatch: "Şifreler Uyuşmuyor!",
    linkNotFound: "Link Bulunamadı!",
    ownerNotAllowed: "Sahiplik İzin Verilmiyor!",
    pathMustBeString: "Yol Dize Olmalı!",
    languageIdMustBePositiveNumber: "Dil Kimliği Pozitif Sayı Olmalıdır!",
    roleCanNotDeletedSomeUsersHasIt: "Rol Silinemez. Bazı Kullanıcılar Bu Role Sahiptir!",
    roleNotFound: "Rol Bulunamadı!",
    roleMustBeSent: "Rol Gönderilmeli!",
    postNotFound: "Gönderi Bulunamadı!",
    slugIdMustBePositiveNumber: "Slug Kimliği Pozitif Sayı Olmalıdır!",
    userIdMustBePositiveNumber: "Kullanıcı Kimliği Pozitif Sayı Olmalıdır!",
    statusNotAllowed: "Durum Bilgisi İzin Verilmiyor!",
    getNotAllowed: "Get İzin Verilmiyor!",
    optionNotFound: "Seçenek Bulunamadı!",
    optionsNotFound: "Seçenekler Bulunamadı!",
    typeMustBeString: "Tür Dize Olmalı!",
    typeIdMustBeInteger: "Tür Kimliği Tam Sayı Olmalıdır!",
    keyMustBeString: "Anahtar Dize Olmalı!",
    categoryNotFound: "Kategori Bulunamadı!",
    fileIdMustBePositiveNumber: "Dosya Kimliği Pozitif Sayı Olmalıdır!",
    parentIdMustBePositiveNumber: "Ebeveyn Kategory Kimliği Pozitif Sayı Olmalıdır!",
    autoLinkNotFound: "Otomatik Bağlantı Bulunamadı!",
    wordMustBeString: "Kelime Dize Olmalı!",
    uriMustBeString: "Uri Dize Olmalı!",
  }
}