export default {
  title: {
    home: "Ana sayfa",
    dashboard: "Gösterge Paneli",
    options: "Ayarlar",
    logout: "Çıkış",
    users: "Kullanıcılar",
    layouts: "Düzenler",
    fullName: "İsim Soyisim",
    email: "Eposta",
    password: "Şifre",
    retypePassword: "Şifre tekrar",

    description: "Açıklama",
    firstName: "İsim",
    lastName: "Soyisim",
    role: "Rol",
    username: "Kullanıcı adı",
    nickname: "Takma ad",
    image: "Resim",
    createdAt: "Oluşturulma zamanı",
    status: "Durum",
  },
  any: {
    title: "Başlık",
    content: "İçerik",
    search: "Ara",
    addNew: "Yeni Ekle",
    save: "Kaydet",
    body: "Gövde",
    noElementFound: "Öğe Bulunamadı!",
    shownRecord: "Sayfada gösterilen kayıt:",
    
    customize: "Özelleştir",
    darkMode: "Karanlık Mod",
    noBorder: "Çerçeve Yok",
    fixed: "Sabit",
    collapsed: "Daralt",
    navFlat: "Düz Menu",
    navLegacy: "Miras Menu",
    navCompact: "Sıkı Menu",
    navChildIndent: "Menu Alt Girinti",
    navChildHideOnCollapse: "Menü Daraltıldığında Alt Elemanı Gizle",
    disableHoverFocusAutoExpand: "Hover/Odak Otomatik Genişletmeyi Devre Dışı Bırak",
    headerOptions: "Başlık Seçenekleri",
    sidebarOptions: "Kenarlık Seçenekleri",
    footerOptions: "Altbilgi Seçenekleri",
    smallTextOption: "Küçük Metin Seçenekleri",
    navbarVariants: "Menü Varyantları",
    sidebarVariants: "Kenarlık Varyantları",
    brandLogoVariants: "Marka Logo Varyantları",
    noneSelected: "Hiçbiri",
    primary: "Birincil",
    secondary: "İkincil",
    info: "Bilgi",
    warning: "Uyarı",
    success: "Başarı",
    danger: "Tehlike",
    indigo: "Çivit",
    purple: "Mor",
    pink: "Pembe",
    navy: "Lacivert ",
    lightblue: "Açık Mavi",
    cyan: "Camgöbeği",
    dark: "Karanlık",
    grayDark: "Koyu Gri",
    gray: "Gri",
    light: "Açık",
    white: "Beyaz",
    orange: "Turuncu",
    fuchsia: "Fuşya",
    maroon: "Bordo",
    lime: "Limon Yeşili",
    teal: "Deniz Mavisi",
    olive: "Zeytin Yeşili",
  },
  footer: {
    text: "Ne isterseniz",
    rights: "Tüm Hakları Saklıdır.",
    copyright: "Telif Hakkı"
  },
  login: {
    message: "Oturumunuzu başlatmak için giriş yapın",
    rememberMe: "Beni Hatırla",
    signIn: "Giriş",
    forgetPassword: "Şifremi unuttum",
    registerNew: "Yeni üyelik kaydı",
  },
  register: {
    message: "Yeni üyelik kaydı",
    register: "kaydol",
    alreadyMember: "Zaten üyeyim",
  },
  password: {
    message: "Şifrenizi mi unuttunuz? Burdan kolayca şifre alabilirsiniz.",
    requestNew: "Yeni şifre isteği",
    login: "Giriş",
  },
  table: {
    title: "Title",
    description: "Description",
    firstName: "First Name",
    lastName: "Last Name",
    fullName: "Full Name",
    role: "Role",
    username: "Username",
    nickname: "Nickname",
    email: "Email",
    image: "Image",
    createdAt: "Created At",
    status: "Status",
  }
}