export default {
  title: {
    home: "Home",
    dashboard: "Dashboard",
    options: "Options",
    users: "Users",
    logout: "Logout",
    layouts: "Layouts",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    retypePassword: "Retype password",

    description: "Description",
    firstName: "First Name",
    lastName: "Last Name",
    role: "Role",
    username: "Username",
    nickname: "Nickname",
    image: "Image",
    createdAt: "Created At",
    status: "Status",
  },
  any: {
    title: "Title",
    content: "Content",
    search: "Search",
    addNew: "Add New",
    save: "Save",
    body: "Body",
    noElementFound: "No Element Found!",
    shownRecord: "The record shown on the page:",
    
    customize: "Customize",
    darkMode: "Dark Mode",
    noBorder: "No Border",
    fixed: "Fixed",
    collapsed: "Collapsed",
    navFlat: "Nav Flat",
    navLegacy: "Nav Legacy",
    navCompact: "Nav Compact",
    navChildIndent: "Nav Child Indent",
    navChildHideOnCollapse: "Nav Child Hide On Collapse",
    disableHoverFocusAutoExpand: "Disable Hover/Focus Auto-Expand",
    headerOptions: "Header Options",
    sidebarOptions: "Sidebar Options",
    footerOptions: "Footer Options",
    smallTextOption: "Small Text Options",
    navbarVariants: "Navbar Variants",
    sidebarVariants: "Sidebar Variants",
    brandLogoVariants: "Brand Logo Variants",
    noneSelected: "None Selected",
    primary: "Primary",
    secondary: "Secondary",
    info: "Info",
    warning: "Warning",
    success: "Success",
    danger: "Danger",
    indigo: "Indigo",
    purple: "Purple",
    pink: "Pink",
    navy: "Navy",
    lightblue: "Lightblue",
    cyan: "Cyan",
    dark: "Dark",
    grayDark: "Gray dark",
    gray: "Gray",
    light: "Light",
    white: "White",
    orange: "Orange",
    fuchsia: "Fuchsia",
    maroon: "Maroon",
    lime: "Lime",
    teal: "Teal",
    olive: "Olive",
  },
  footer: {
    text: "Anything you want",
    rights: "All rights reserved.",
    copyright: "Copyright"
  },
  login: {
    message: "Sign in to start your session",
    rememberMe: "Remember Me",
    signIn: "Sign In",
    forgetPassword: "I forgot my password",
    registerNew: "Register a new membership",
  },
  register: {
    message: "Register a new membership",
    register: "Register",
    alreadyMember: "I already have a membership",
  },
  password: {
    message: "You forgot your password? Here you can easily retrieve a new password.",
    requestNew: "Request new password",
    login: "Login",
  },
}